### ISSUE TITLE
can't (consistently) use numbers for section headings (Windows 7)

### ISSUE THREAD

**Issue by ergodicbreak** [rundis/AsciiLight#1]
to reproduce:
1. download latest LT Windows binary (0.7.2, binary 0.8.6) to Windows 7 OS
2. install AsciiLight
3. create new file and save as test.adoc
4. Edit text:

``` asciidoc
= Test

== Test123

== 1234

== .1234

== a1234

== !1234
```

(weird how GH's highlighter doesn't handle that very well?) and run command for AsciiLight to watch editor, which then renders it as:

> Test
> 
> .1234
> 
> !1234

I'm going to try running the file just through asciidoctor.js when I get some time, I suspect some cross-platform JS/regex wonkiness. 

Thanks for the plugin btw, I'd never used asciidoc until now and I really like the documents you can make with it!

**Comment by ergodicbreak** [comment]
Some more strangeness -- I copied part of the sample distributed with the plugin to a gist, here

https://gist.github.com/ergodicbreak/8b97c5bb5ec054481ca5

Rendered by GH this looks normal; rendered in LT I don't see any section titles in the main text. However I do see the section titles in the TOC (and in the TOC section titles numbers render OK).

**Comment by rundis** [comment]
seems to be a css issue with text-rendering: optimizeLegibility; on windows7 with chrome 64bit... 
Until I make a release you can remove this css property from headings in adoc.css

**Comment by ergodicbreak** [comment]
Great, nice catch! May I ask how you tracked this down?

**Comment by rundis** [comment]
Sure:
- Brushed the cowebs of my parallells installation
- added various js/alert in asciilight.cljs (couldn't get println to work on LightTable windows) to scope down the error (asciidoctor.js gave valid html back -> the html markup for the headings was indeed added to the relevant dom node in the preview -> voila must be some css related issue
- uncommented all styles in adoc.css then gradually adding styles to see when things went pear shape

**Comment by rundis** [comment]
This should be fixed in version 0.3.0.
